// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package pgsql

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Video struct {
	ID        pgtype.UUID
	Playlist  string
	Videoid   string
	Title     string
	Author    string
	Thumbnail string
	Duration  string
}
